blank_issues_enabled: false
contact_links:
  - name: 'ðŸ’¬ Get Help'
    url: https://github.com/barvian/number-flow/discussions/new?category=help
    about: If you can't get something to work the way you'd like, open a question in the discussion forums.
  - name: 'ðŸ’¡ Feature Request'
    url: https://github.com/barvian/number-flow/discussions/new?category=ideas
    about: 'Suggest any ideas you have using the discussion forums.'
  # - name: Bug Report
  #   url: https://github.com/barvian/number-flow/issues/new
  #   about: If something is clearly broken or not working as documented, create a bug report.
  # - name: Documentation Issue
  #   url: https://github.com/tailwindlabs/tailwindcss.com
  #   about: 'For documentation issues, suggest changes on our documentation repository.'
